version: 2
updates:
  # Enable version updates for pip
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(pip)"
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 2
